#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

disclaimer="\n// Generated by Seedcloud."
settings_php="${DRUPAL_SITE_DIR}/settings.php"
sites_php="${DRUPAL_ROOT}/sites/sites.php"

mkdir -p "${DRUPAL_SITE_DIR}"
chmod 755 "${DRUPAL_SITE_DIR}" || true

# Include seedcloud.settings.php
if [[ ! -f "${settings_php}" ]]; then
    echo -e "<?php\n\n" > "${settings_php}"
fi

if [[ $( grep -ic "seedcloud.settings.php" "${settings_php}" ) -eq 0 ]]; then
    chmod 644 "${settings_php}"
    echo -e "${disclaimer}" >> "${settings_php}"
    echo -e "include '${SEEDCLOUD_DIR_CONF}/seedcloud.settings.php';" >> "${settings_php}"
fi

# Include seedcloud.sites.php for Drupal 7 and 8.
if [[ "${DRUPAL_SITE}" != "default" ]]; then
    if [[ "${DRUPAL_VERSION}" == "8" ]] || [[ "${DRUPAL_VERSION}" == "7" ]]; then
        if [[ $( grep -ic "seedcloud.sites.php" "${sites_php}" ) -eq 0 ]]; then
            echo -e "${disclaimer}" >> "${sites_php}"
            echo -e "include '${SEEDCLOUD_DIR_CONF}/seedcloud.settings.php';" >> "${sites_php}"
        fi
    fi
fi

DRUPAL_SITE_FILES="${DRUPAL_SITE_DIR}/files"
mkdir -p "${DRUPAL_SITE_FILES}"

# Sync and symlink files dir if it's not symlink already.
if [[ ! -L "${DRUPAL_SITE_FILES}" ]]; then
    mkdir -p "${SEEDCLOUD_DIR_FILES}/private"
    mkdir -p "${SEEDCLOUD_DIR_FILES}/public"

    if [[ -d "${DRUPAL_SITE_FILES}/private" ]]; then
        rsync -rlt --force "${DRUPAL_SITE_FILES}/private/" "${SEEDCLOUD_DIR_FILES}/private/"
    fi

    if [[ -d "${DRUPAL_SITE_FILES}/public" ]]; then
        rsync -rlt --force "${DRUPAL_SITE_FILES}/public/" "${SEEDCLOUD_DIR_FILES}/public/"
    else
        rsync -rlt --force "${DRUPAL_SITE_FILES}/" "${SEEDCLOUD_DIR_FILES}/public/"
    fi

    rm -rf "${DRUPAL_SITE_DIR}/files"
    ln -sf "${SEEDCLOUD_DIR_FILES}/public" "${DRUPAL_SITE_DIR}/files"
fi
